In [22]:
import numpy as np

Question 1:

In [23]:
import numpy as np

A = np.zeros((4,4))
A[0,:] = [1,1,1,1]
A[1,:] = [.14,.2,.2,.1]
A[2,:] = [.45,-.55,0,0]
A[3,:] = [0,1,0,0]
A

array([[ 1.  ,  1.  ,  1.  ,  1.  ],
       [ 0.14,  0.2 ,  0.2 ,  0.1 ],
       [ 0.45, -0.55,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ]])

In [24]:
b = np.array([250,37.5,0,62.5])
b

array([250. ,  37.5,   0. ,  62.5])

In [25]:
xyz = np.linalg.solve(A,b)
xyz

array([76.38888889, 62.5       , 31.94444444, 79.16666667])

Question 2:

In [26]:
A = np.zeros((10,5))
A[0,:] = [1,-1,0,0,0]
A[1,:] = [1,0,-1,0,0]
A[2,:] = [1,0,0,-1,0]
A[3,:] = [1,0,0,0,-1]
A[4,:] = [0,1,-1,0,0]
A[5,:] = [0,1,0,-1,0]
A[6,:] = [0,1,0,0,-1]
A[7,:] = [0,0,1,-1,0]
A[8,:] = [0,0,1,0,-1]
A[9,:] = [0,0,0,1,-1]
A

array([[ 1., -1.,  0.,  0.,  0.],
       [ 1.,  0., -1.,  0.,  0.],
       [ 1.,  0.,  0., -1.,  0.],
       [ 1.,  0.,  0.,  0., -1.],
       [ 0.,  1., -1.,  0.,  0.],
       [ 0.,  1.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0., -1.],
       [ 0.,  0.,  1., -1.,  0.],
       [ 0.,  0.,  1.,  0., -1.],
       [ 0.,  0.,  0.,  1., -1.]])

In [27]:
b = np.array([-45,-3,-31,-45,18,8,20,2,-27,-38])
b

array([-45,  -3, -31, -45,  18,   8,  20,   2, -27, -38])

In [28]:
M = np.matmul(np.transpose(A),A)
y = np.matmul(np.transpose(A),b)

In [29]:
M[-1,:] = [1,1,1,1,1]
y[-1] = 0

In [30]:
a = np.linalg.solve(M,y)
a

array([-24.8,  18.2,  -8. ,  -3.4,  18. ])

In [31]:
y

array([-124.,   91.,  -40.,  -17.,    0.])

Question 3:

In [6]:
A = np.zeros((20,20))
for i in range(20):
    for j in range(20):
        if i > j:
            A[i,j] = (j+1)/(i+1)
        else:
            A[i,j] = (i+1)/(j+1)
        if A.all() == A.T.all():
            print('Symmetric')
        else:
            print('Asymmetric')

Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric
Symmetric


Question 4:

In [4]:

C = np.linalg.inv(A)
d = np.array([1,2,3,4,5,6,7,8,9,10,10,9,8,7,6,5,4,3,2,1])

x = np.linalg.solve(A,np.matmul(C,d))
round(x[9],1)

20.1